nelmio_api_doc:
    documentation:
        info:
            title: Comunee — backend
            description:
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/documentation$) # Accepts routes under /api except /api/doc
